-- pastebin run -f cyF0yhXZ
-- von Nex4rius
-- https://github.com/Nex4rius/Nex4rius-Programme/

-- label -> angezeigter Name

return {
["Helium3"]                      = "Helium-3",
["fluidair"]                     = "Air",
["fluidchlorine"]                = "Chlorine",
["fluidgasgas"]                  = "Refinery Gas",
["fluidglue"]                    = "Glue",
["fluidhelium3"]                 = "Helium-3",
["fluidliquidcrackedheavyfuel"]  = "Cracked Heavy Fuel",
["fluidliquidcrackedlightfuel"]  = "Cracked Light Fuel",
["fluidliquidepichlorhydrin"]    = "Epichlorhydrin",
["fluidliquidheavyfuel"]         = "Heavy Fuel",
["fluidliquidheavyoil"]          = "Heavy Oil",
["fluidliquidlightfuel"]         = "Light Fuel",
["fluidliquidlpg"]               = "LPG",
["fluidliquidnaphtha"]           = "Naphtha",
["fluidliquidsulfuricgas"]       = "Sulfuric Gas",
["fluidliquidsulfuricheavyfuel"] = "Sulfuric Heavy Fuel",
["fluidliquidsulfuriclightfuel"] = "Sulfuric Light Fuel",
["fluidliquidtoluene"]           = "Toluene",
["fluidmercury"]                 = "Mercury",
["fluidmoltenepoxid"]            = "Molten Epoxid",
["fluidmoltenplastic"]           = "Molten Polyethylene",
["fluidmoltenredstone"]          = "Molten Redstone",
["fluidmoltenrubber"]            = "Molten Rubber",
["fluidmoltensolderingalloy"]    = "Molten Soldering Alloy",
["fluidmoltenneodymium"]         = "Molten Neodymium",
["fluidmoltentungsten"]          = "Molten Tungsten",
["fluidmoltenplutonium244"]      = "Molten Plutonium 244",
["fluidmoltencarbon"]            = "Molten Carbon",
["fluidmoltenberyllium"]         = "Molten Beryllium",
["fluidmoltenuranium238"]        = "Molten Uranium 238",
["fluidmoltenamericium"]         = "Molten Americium",
["fluidmolteneuropium"]          = "Molten Europium",
["fluidmoltenlutetium"]          = "Molten Lutetium",
["fluidmoltenthorium"]           = "Molten Thorium",
["fluidmoltenplatinum"]          = "Molten Platinum",
["fluidmoltengold"]              = "Molten Gold",
["fluidmoltenpotassium"]         = "Molten Potassium",
["fluidmolteniridium"]           = "Molten Iridium",
["fluidmoltenlithium"]           = "Molten Lithium",
["fluidmoltenaluminium"]         = "Molten Aluminium",
["fluidmoltenchrome"]            = "Molten Chrome",
["fluidmoltenmanganese"]         = "Molten Manganese",
["fluidmoltenosmium"]            = "Molten Osmium",
["fluidmoltensilicon"]           = "Molten Silicon",
["fluidmoltenmagnesium"]         = "Molten Magnesium",
["fluidnitrogendioxide"]         = "Nitrogen Dioxide",
["fluidsulfuricacid"]            = "Sulfuric Acid",
["lpg"]                          = "LPG",
["plastic"]                      = "Liquid Plastic",
}
