version = "1.4.5"
component = require("component")
fs = require("filesystem")
if component.isAvailable("internet") then
  fs.makeDirectory("/stargate")
  print("- Internet Card        ok (optional)")
  print("")
  os.execute("wget -f 'https://raw.githubusercontent.com/DarknessShadow/Stargate-Programm/test/stargate/autorun.lua' autorun.lua")
  print("")
  os.execute("wget -f 'https://raw.githubusercontent.com/DarknessShadow/Stargate-Programm/test/stargate/control.lua' stargate/control.lua")
  print("")
  os.execute("wget -f 'https://raw.githubusercontent.com/DarknessShadow/Stargate-Programm/test/stargate/compat.lua' stargate/compat.lua")
  print("")
  os.execute("wget -f 'https://raw.githubusercontent.com/DarknessShadow/Stargate-Programm/test/stargate/config.lua' stargate/config.lua")
  print("")
  os.execute("wget -f 'https://raw.githubusercontent.com/DarknessShadow/Stargate-Programm/test/stargate/reset.lua' stargate/reset.lua")
  print("")
  os.execute("wget 'https://raw.githubusercontent.com/DarknessShadow/Stargate-Programm/test/stargate/addresses.lua' stargate/addresses.lua")
  print("")
  os.execute("wget 'https://raw.githubusercontent.com/DarknessShadow/Stargate-Programm/test/stargate/saveAfterReboot.lua' stargate/saveAfterReboot.lua")
  print("")
  f = io.open ("stargate/addresses.lua", "r")
  readAddresses = f:read(10000)
  AdressesLength = string.len(readAddresses)
  f:close ()
  if string.sub(readAddresses, AdressesLength, AdressesLength) == " " then
    f = io.open ("stargate/addresses.lua", "a")
    f:seek ("end", -1)
    f:write("")
    f:close ()
  end
else
  print("- Internet Card        Missing (optional)")
end
dofile("stargate/control.lua")
