os.execute("wget -f 'https://raw.githubusercontent.com/DarknessShadow/Stargate-Programm/test/autorun.lua' autorun.lua")
print("")
os.execute("wget -f 'https://raw.githubusercontent.com/DarknessShadow/Stargate-Programm/test/control.lua' control.lua")
print("")
os.execute("wget -f 'https://raw.githubusercontent.com/DarknessShadow/Stargate-Programm/test/compat.lua' compat.lua")
print("")
os.execute("wget -f 'https://raw.githubusercontent.com/DarknessShadow/Stargate-Programm/test/config.lua' config.lua")
print("")
os.execute("wget -f 'https://raw.githubusercontent.com/DarknessShadow/Stargate-Programm/test/reset.lua' reset.lua")
print("")
os.execute("wget 'https://raw.githubusercontent.com/DarknessShadow/Stargate-Programm/test/addresses.lua' addresses.lua")
print("")
os.execute("wget 'https://raw.githubusercontent.com/DarknessShadow/Stargate-Programm/test/saveAfterReboot.lua' saveAfterReboot.lua")
f = io.open ("addresses.lua", "r")
readAddresses = f:read(10000)
AdressesLength = string.len(readAddresses)
f:close ()
if string.sub(readAddresses, AdressesLength, AdressesLength) == " " then
  f = io.open ("addresses.lua", "a")
  f:seek ("end", -1)
  f:write("")
  f:close ()
end
dofile("control.lua")
