ersetzen = {
  ["On"]                  = irisKontrolleNameAn,
  ["Off"]                 = irisKontrolleNameAus,
  ["Open"]                = irisNameOffen,
  ["Opening"]             = irisNameOeffnend,
  ["Closed"]              = irisNameGeschlossen,
  ["Closing"]             = irisNameSchliessend,
  ["Offline"]             = irisNameOffline,
  ["Override"]            = Eingriff,
  ["Manual"]              = manueller,
  ["Request"]             = aufforderung,
  ["Disconnect"]          = stargateAbschalten,
  ["Stargate"]            = stargateName,
  ["Control"]             = IrisSteuerungName,
}
